[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
proto = {path="../proto"}
netcode.workspace = true
tokio.workspace = true
uuid = {version = "1.8.0", features = ["v4"]}
log = "0.4.21"
simple_logger = "5.0.0"